# https://github.com/marketplace/actions/publish-nuget
name: Publish JsonSchema.Net Languages
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - JsonSchema/nuspec/**
      - JsonSchema/Localization/**
  workflow_dispatch:

jobs:
  build-localizations:
    name: build localizations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get-localized-nuspecs
        run: |
          NUSPEC_FILES=$(echo -n '[' ; ls JsonSchema/nuspec/ --format=commas|sed -e 's/^/\"/'|sed -e 's/,$/\",/'|sed -e 's/\([^,]\)$/\1\"\]/'|sed -e 's/, /\", \"/g')
          echo ${NUSPEC_FILES}
          echo "::set-output name=NUSPEC_FILES::${NUSPEC_FILES}"
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      # Publish
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        # Localization build automatically moves localization DLLs into nuspec/ folder
        run: dotnet build JsonSchema/JsonSchema.csproj --configuration Localization --no-restore
      - name: archive packages
        uses: actions/upload-artifact@v2
        with:
          name: localization-artifacts
          path: JsonSchema/nuspec/**/*
    outputs:
      matrix: ${{ steps.get-localized-nuspecs.outputs.NUSPEC_FILES }}
  verify-matrix:
    needs: build-localizations
    runs-on: ubuntu-latest
    steps:
      - run: |
          matrix='${{ needs.build-localizations.outputs.matrix }}'
          echo $matrix
  publish-localizations:
    needs: build-localizations
    name: build, pack & publish localizations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nuspec: ${{ fromJson(needs.build-localizations.outputs.matrix) }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: '6.x'
      - name: publish localization
        run: |
          nuget pack ${{ matrix.nuspec }} -OutputDirectory nupkg/
      - name: archive packages
        uses: actions/upload-artifact@v2
        with:
          name: archive-packages
          path: nupkg/*.nupkg
